name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Publish Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login in docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_DEPLOY_KEY }}

      - name: Strip tags name
        id: strip
        if: ${{ contains(github.ref, 'refs/tags/') }}
        # Strip prefix 'refs/tags' and suffix '#{worker_name}' then set into output
        run: STRIP=${GITHUB_REF#refs/tags/}; echo "::set-output name=tags_name::${STRIP%#*}"

      - name: Build & Push Docker Images with latest tag
        uses: docker/build-push-action@v4
        if: ${{ contains(github.ref, 'refs/tags/') }}
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            docker.io/charkchalk/backend:latest
            docker.io/charkchalk/backend:${{ steps.strip.outputs.tags_name }}
