name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Publish Project
    runs-on: ubuntu-latest

    steps:
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login in docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_DEPLOY_KEY }}

      - name: Build & Push Docker Images with latest tag
        uses: docker/build-push-action@v4
        if: ${{ contains(github.ref, 'refs/tags/') }}
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/charkchalk/backend:latest
            docker.io/charkchalk/backend:${{ github.ref_name }}
