name: Java Unit Tests

on:
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: Test Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Test with JUnit
        run: ./gradlew test
